### ISSUE TITLE
Implement Action Servers and Client

### ISSUE THREAD

**Issue by TimWhiting** [TimWhiting/dartros#12]
I already implemented much of this functionality. (Following the code in nodejs implementation for the most part). 

I was about to test it, when I ran into some type errors with the generated messages. Most of the action message generation process is still in the gendart repository, there should just be a little work required to understand and make this work.

@knuesel 
I won't be able to get to this myself in the near future, since we aren't currently using actions in my lab. Totally willing to accept PRs for this though. Let me know if you need some pointers in the right direction for getting this implemented.

**Comment by knuesel** [comment]
OK I'll try to get it working! For `gendart` would you be open to a substantial refactoring? I was investigating a problem with packages that define a service but no message (`msg_list` throws in this case because the `-I` flag doesn't pass the package directory) and I think the logic could be made more robust by better using the information available from CMake. This could also avoid regenerating the same files for every message file. But there might be a reason why `gennodejs` does it like that, so I'm not sure it will work... but I'd like to try 😊

**Comment by TimWhiting** [comment]
Yeah, I'm open to a substantial refactoring. The current is based off of gennodejs, and I wasn't too familiar with the CMake process for generating messages and how it specified message dependencies, so I just changed what I needed to to get it working. It seems like rosnodejs has switched to a more dynamic message serialization / deserialization process rather than relying much on the generation process anymore. Just make sure that when you test it out that you test it with a message package that depends on another message package, and make sure that it generates both. Now that we depend on the pub versions of sensor_msgs and geometry_msgs it can't be one of those though. Also try deleting the old messages every once in awhile while you are testing to make sure that there are no errors when generating messages from stratch.

I have a workspace repository called dartros_ws which contains a .rosinstall file with the repositories I use to test changes to dartros. Feel free to use that, and update the workspace with whatever you need to test message generation more fully. Also make sure you pull the most recent changes to gendart. I made some this morning before generating and publishing geometry_msgs and sensor_msgs.

**Comment by knuesel** [comment]
I see, thanks for the advice.

**Comment by TimWhiting** [comment]
If you are going to be updating the message generation, we might also want to look into running dart format on the generated files in case any user tries inspecting the generated classes. I think I did pretty well on formatting manually, but it might improve it just slightly.
