### ISSUE TITLE
Issues about ROS service as client

### ISSUE THREAD

**Issue by jeff214103** [TimWhiting/dartros#31]
Hi, I am using ubuntu 18.04, ROS melodic, and as well as null safe version of dart gen.
I have generated a message containing three types of data in response.
1. int robot_id
2. string robot_type
3. double robot_size

It is okay to call using rosservice call in terminal, but when I run using dartros, it raise an error of 

Unhandled exception:
Bad state: Not enough bytes to read.
#0      ByteDataReader.read (package:buffer/buffer.dart:418:7)
#1      ByteDataReaderRosDeserializers.readString (package:dartros_msgutils/src/msg_utils.dart:74:34)
#2      GetRobotInfoResponse.deserialize (package:dartros_msgs/src/srvs/GetRobotInfo.dart:106:30)
#3      ServiceClient._sendRequest (package:dartros/src/service_client.dart:130:38)
<asynchronous suspension>
#4      ServiceClient._executeCall (package:dartros/src/service_client.dart:81:20)
<asynchronous suspension>

![Screenshot from 2021-05-14 12-50-35](https://user-images.githubusercontent.com/37507767/118222899-0e7ab300-b4b3-11eb-89bb-fcc64ef74deb.png)

I am not sure where to problem caused, as after some time of tracing, I notice the call cross more than about 3 repositories.  

For your info, I am using python for server, and the srv looks like this.
![Screenshot from 2021-05-14 12-57-04](https://user-images.githubusercontent.com/37507767/118223469-f22b4600-b4b3-11eb-962a-f548ad18a6cf.png)

Also, a test result that if I provide nothing to robot_type, the error will not be appeared, but the robot_id will received wrong as 512. Thank you so much if any help can be provided.

**Comment by TimWhiting** [comment]
I will look into this issue today

**Comment by jeff214103** [comment]
The latest discovery is that the issue is happened due to Endian problem.
By editing lib/src/service_client.dart, in _sendRequest function, add Endian.little parameter to ByteDataReader will solve the issue.
However, I do not really understand why it only happened in service as a client, but none of others such as publisher, subscriber, or service as server.
Hope this information helps you fix the issue.

**Comment by TimWhiting** [comment]
Thanks for finding that. Yeah, all ByteDataReaders / Writers need to be little endian for ROS. It was probably misinterpreting the size portion of the packet which would definitely cause that exception. The other's already were little endian which is why there was no problem with them.

Published version `0.1.2` with the fix
