### ISSUE TITLE
Determine whether to publish sensor_msgs and geometry_msgs

### ISSUE THREAD

**Issue by TimWhiting** [TimWhiting/dartros#4]
These are two pretty popular packages that also might benefit from being published to pub.dev so that other dart packages can be created to build some infrastructure around those messages.

For example a cv_bridge type package would need sensor_msgs published. And I can imagine some good extension methods for the geometry_msgs. 

Any feedback? I don't currently need them published now, but will if there is demand.

**Comment by knuesel** [comment]
I think these two are worth publishing, to help build the ecosystem as you say and also to reduce friction when getting started. Also sensor_msgs is already used by `example/pub_image.dart`, once published we can uncomment it from the `dev_dependencies` so people can run the example.

**Comment by TimWhiting** [comment]
These are now published. And the gendart script has been updated to depend on the pub versions if a message depends on one of those packages. I'll uncomment the dev_dependency in dartros, and publish a new version of dartros with all of your fixes.
