### ISSUE TITLE
publish message failed 

### ISSUE THREAD

**Issue by Reinoal** [TimWhiting/dartros#50]
seviceClient ok, subscribe ok. set param ok.
but advertise failed , debug class publisher_impl members of subClients and udpSubClients is empty , so its can't send anything to topic.
code: 
   final twist = Twist(linear: Vector3(), angular: Vector3());
   final pub = nd.advertise('topic name', Twist.$prototype);
   pub.publish(twist);

I need your help thanks!!!!!

**Comment by Reinoal** [comment]
yes I using ros1 and have a roscore running. 
I use dartros on android phone and app connect to robot in same network, 
ros:
   rostopic info /vel_input
Type: geometry_msgs/Twist

Publishers:
* /myRosNode(http://192.168.3.41:16163/)

Subscribers:
* /vel_smoother (http://hostname:44023/)

myRosNode is my app, I advertise msgs to this topic and echo, but nothing print out.

**Comment by TimWhiting** [comment]
Are you setting the ROS_MASTER_URI on both the robot and the app? As well as the ROS_IP?

See this issue:
https://github.com/TimWhiting/dartros/issues/39

**Comment by Reinoal** [comment]
I made a mistake ， I use android simulator to test this.  It works fine on a real device. 
At the flutter app this project was very important to me, Thank you so much for this project.
