### ISSUE TITLE
android connect success, iOS connect error

### ISSUE THREAD

**Issue by Reinoal** [TimWhiting/dartros#51]
android is ok ,but iOS show errors, and IOS info file add NSApptransportSecurity:NSAllowsArbitraryLoads value set YES.
ros masterIp:http://192.168.0.7:11311
error msg:
flutter: \^[[38;5;196m│ Error while registering publisher /rosout: Connection failed<…>
flutter: \^[[38;5;196m│ #0      IOClient.send (package:http/src/io_client.dart:94:7)<…>
flutter: \^[[38;5;196m│ <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #1      BaseClient.sendUnstreamed (package:http/src/base_client.dart:93:32)<…>
flutter: \^[[38;5;196m│ <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #2      call (package:xml_rpc/src/client.dart:51:7)<…>
flutter: \^[[38;5;196m│ <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #3      _rpcCall (package:mm_controller/libs/dartros-master/lib/src/ros_xmlrpc_client.dart:96:18)<…>
flutter: \^[[38;5;196m│ <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #4      RosXmlRpcClient.registerPublisher (package:mm_controller/libs/dartros-master/lib/src/ros_xmlrpc_client.dart:266:8)<…>
flutter: \^[[38;5;196m│ <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #5      PublisherImpl.register (package:mm_controller/libs/dartros-master/lib/src/impl/publisher_impl.dart:111:20)<…>
flutter: \^[[38;5;196m│ <asynchronous suspension><…>
flutter: \^[[38;5;196m│ <…>

**Comment by TimWhiting** [comment]
I'm sorry, I have no iOS device, so I don't know how to help here. You are welcome to submit a PR if you figure out the issue, maybe submit a PR for documentation for debugging help for future users as well.

**Comment by Reinoal** [comment]
OK thanks , if I solve this pr, I'll report it
